export const REGION = [
  { value: 1, name: "Abia" },
  { value: 2, name: "Adamawa" },
  { value: 3, name: "Akwa Ibom" },
  { value: 4, name: "Anambra" },
  { value: 5, name: "Bauchi" },
  { value: 6, name: "Bayelsa" },
  { value: 7, name: "Benue" },
  { value: 8, name: "Borno" },
  { value: 9, name: "Cross River" },
  { value: 10, name: "Delta" },
  { value: 11, name: "Ebonyi" },
  { value: 12, name: "Edo" },
  { value: 13, name: "Ekiti" },
  { value: 14, name: "Enugu" },
  { value: 15, name: "FCT (Abuja)" },
  { value: 16, name: "Gombe" },
  { value: 17, name: "Imo" },
  { value: 18, name: "Jigawa" },
  { value: 19, name: "Kaduna" },
  { value: 20, name: "Kano" },
  { value: 21, name: "Katsina" },
  { value: 22, name: "Kebbi" },
  { value: 23, name: "Kogi" },
  { value: 24, name: "Kwara" },
  { value: 25, name: "Lagos" },
  { value: 26, name: "Nasarawa" },
  { value: 27, name: "Niger" },
  { value: 28, name: "Ogun" },
  { value: 29, name: "Ondo" },
  { value: 30, name: "Osun" },
  { value: 31, name: "Oyo" },
  { value: 32, name: "Plateau" },
  { value: 33, name: "Rivers" },
  { value: 34, name: "Sokoto" },
  { value: 35, name: "Taraba" },
  { value: 36, name: "Yobe" },
  { value: 37, name: "Zamfara" },
];
   

export const PARTIES = [
  { value: 1, name: "APC" },
  { value: 2, name: "LP" },
  { value: 3, name: "PDP" },
  { value: 4, name: "NNPC" },
  { value: 5, name: "AAC" },
  { value: 6, name: "APGA" },
  { value: 7, name: "ADP" },
  { value: 8, name: "ADC" },
];